<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="BG4WS0628" name="drivers.Driver" tests="2" failures="0" timestamp="19 Jul 2018 12:16:29 GMT" time="22.203" errors="1">
  <testcase name="TC_01" time="10.782" classname="drivers.Driver"/>
  <testcase name="TC_02" time="11.421" classname="drivers.Driver">
    <error type="java.lang.AssertionError" message="test assert failure&#039; DOES NOT match with actual value &#039;false">
      <![CDATA[java.lang.AssertionError: test assert failure' DOES NOT match with actual value 'false
	at com.testng.SonnetTestNGAssertions.throwException(SonnetTestNGAssertions.java:279)
	at com.testng.SonnetTestNGAssertions.equals(SonnetTestNGAssertions.java:77)
	at pom.Sample.CounterWebApp2(Sample.java:37)
	at drivers.Driver.TC_02(Driver.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
]]>
    </error>
  </testcase> <!-- TC_02 -->
</testsuite> <!-- drivers.Driver -->
